/**
 * Decalre all the validation strings here for using in throughout the app.
 */

export const Validation = {
    appName: 'React Native template',
    // ...basicValidations,
    // ...networkHandling,
    validEmail: 'Please enter email address',
    validEmailFormat: 'Please enter a valid email address',
    validNumberFormat: 'Please enter a valid phone number',
    validNumber: 'Please enter phone number',
    validPassword: 'Please enter a password',
    validOldPassword: 'Please enter current password',
    validNewPassword: 'Please enter new password',
    validPasswordDetail:
      'At least 1 Capital Letter & 1 Small Letter | At least 1 Special Character & 1 Number | 6-15 Characters Long',
    validConfirmPassword: 'Please enter confirm password',
    validConfirmPasswordLength: 'Password and Confirm Password must be the same',
    validConfirmPasswordNotMatch: 'New password and confirm password does not match',
    validConfirmNewPassword: 'Please enter confirm password',
    forgotPwdTitle: 'Forgot Password?',
    forgotPwdSubTitle: 'Please enter your email id to reset your \n password.',
    emailId: 'Email ID',
    sendVerifiCode: 'Send Verification Code',
    FirstNameError: 'Please enter your first name',
    validName: 'Please enter valid name',
    LastNameError: 'Please enter your last name',
    validLastName: 'Please enter valid name',
    exceedNameLimit: 'Please enter less than 20 characters',
    MobileNumberError: 'Please enter mobile number',
    validMobileNumber: 'Please enter a valid mobile number',
    verifyCode: 'Verify Code',
    validOneTimePassword: 'Please enter OTP',
    validOneTimeLength: 'Please enter 4 digit valid OTP',
    yearDOB: 'Please enter date/Year',
    validDOB: 'Please enter valid date/Year',
    validGender: 'Please Select Gender',
    validEmailMobileEmail: 'Please enter email',
    acceptTermsCondition: 'Please agree to Terms & Condition',
    pleaseAcceptTerms: 'Please accept Terms & conditions and Privacy Policy',
    wrongEmailOrPassword: 'Wrong email or password. Please try again!',
    wrongNumberOrPassword: 'Wrong mobile number or password. Please try again!',
    emailAddressNotRegistered: 'Email address not registered!',
    mobNumberNotRegistered: 'Mobile Number not registered!',
    passwordResetSuccessfully: 'Password reset successfully!',
    validFirstNameFormat: 'Please enter a valid first name',
    validLastNameFormat: 'Please enter a valid last name',
    validZipCode: 'Please enter a valid zip code',
    enterZipCode: 'Please enter a zip code',
    validAddress: 'Please enter a valid address',
    enterAddress: 'Please enter a address',
    validCity: 'Please enter a valid city',
    enterCity: 'Please enter a city',
    validState: 'Please enter a valid state',
    enterState: 'Please enter a state',
    validFullName: 'Please enter a valid full name',
    enterFullName: 'Please enter full name',
    enterReason: 'Please enter reason',
    enterDescription: 'Please enter description',
    cardNumber: 'Please enter card number',
    cardCvv: 'Please enter cvv number',
    validCvv: 'Please enter valid cvv',
    cardMonth: 'Please select month',
    cardYear: 'Please select year',
    cardExpiry: 'Please select expiry date',
    cardExpiryEnter: 'Card expiration date is required',
    resetNumber: 'Reset Password link is successfully sent to your registered mobile number',
    resetEmail: 'Reset Password link is successfully sent to your registered email address',
    validCardNumber: 'Please enter valid card number',
    validExpiryDate: 'Please enter a valid expiration date',
    talentRoleError: 'Please select your talent role',
    address1Error: 'Please enter your address 1 field',
    address2Error: 'Please enter your address 2 field',
    landmarkError: 'Please enter your landmark',
    cityError: 'Please enter your city',
    pinCodeError: 'Please select your pin code',
    stateError: 'Please select your state',
    districtError: 'Please select your disrict',
    bioError: 'Please enter bio',
    maxRateError: 'Please enter max rate',
    minRateError: 'Please enter min rate',
    filmeNameError: 'Please enter film name',
    brandNameError: 'Please enter brand name',
    filmLinkError: 'Please enter film link',
    pinToTopError: 'Please select pin to top value',
    hideReelError: 'Please select hide from showreel value',
    yearReleaseError: 'Please enter the year of release'
  };
  